### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by mhibti** [myQLM/myqlm-issues#1]
Dear all,
I have an issue with the installation of myqlm.

>pip install myqlm
leads to 

ERROR: Could not find a version that satisfies the requirement qat-variational>=1.1.6 (from myqlm) (from versions: none)
ERROR: No matching distribution found for qat-variational>=1.1.6 (from myqlm)

> pip -V
pip 20.2.3 from /home/user/.local/lib/python3.7/site-packages/pip (python 3.7)
>uname -a
Linux system 4.19.0-11-amd64 myQLM/myqlm.github.io#1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux

What am'I missing ?
Thanks

**Comment by jcjaskula** [comment]
Dear @mhibti,

myqlm has not been packaged for python3.7 yet. Since you are on Linux, you would need to install first python3.6 (64-bit). For that, you can consider using a virtual environment if you wish. Here is one example on how to proceed in the case you have previously installed python3.7 via the 64-bit anaconda distribution.

#Create a virtual environment for python3.6
conda create -n python3.6 python=3.6

#Activate it
conda activate python3.6

#Install myqlm in this (python3.6) virtual environment
pip install myqlm

Please consider other ways to install python3.6 if you do not use the anaconda distribution.

**Comment by mhibti** [comment]
Thank you very much! 
 I will try to do that and give a feedback later.
All the best

**Comment by mhibti** [comment]
Dear Jean Christophe,
Thanks It worked ! 
I had some error messages about updating some libraries. The messages was clear enough to fix them.
There was also some errors when executing some programs, mainly due to some missing latex packages (new machine).
texlive-extra-utils
texlive-pictures
