### ISSUE TITLE
Error when trying to visualize the circuits

### ISSUE THREAD

**Issue by edaruizgu** [myQLM/myqlm-issues#2]
**Describe the bug**
I'm not able to print circuits with %qatdisplay circuit.

**To Reproduce**
I was running the tutorial epr_pair. Everything worked well until it tried to print the circuit.

**Screenshots**
There is a screenshot of the error as an attachment.

**Desktop**
 - OS: Windows 10
 - Browser: Chrome
 
**Additional context**
I installed ' ImageMagick for wand' as sugggested with:

- pip install Wand
- ImageMagick-6.9.11-42-Q16-HDRI-x64-dll.exe | Win64 dynamic at 16 bits-per-pixel component

![error_print_circuits](https://user-images.githubusercontent.com/74904912/99952737-6c3e0600-2d80-11eb-9c32-a1b4ad2c1058.png)

**Comment by amitsaha2806** [comment]
Hello, 

You should try %jsqatdisplay instead of %qatdisplay.

**Comment by SaikatBasu90** [comment]
As you are using windows system, instead of %qatdisplay please use %jsqatdisplay.

**Comment by edaruizgu** [comment]
I tried and it worked, thanks!!

**Comment by edaruizgu** [comment]
I tried and it worked, thanks!!

**Comment by Baptxg** [comment]
Hello,
I am having the same problem. I work on windows and the %qatdisplay doesn't work, but neither does the %jsqatdisplay.
Please see the attached screenshot to see the error message. It says the function is not found.

Thanks for your help

![image](https://user-images.githubusercontent.com/79231081/108278280-190b0200-717b-11eb-8dd8-556c5d6da2fa.png)

**Comment by amitsaha2806** [comment]
Hello,

Our qatdisplay magic requires wand module to display quantum circuits inside Jupyter notebooks (cf. Prerequisites in the documentation)

The wand module requires extra tools to work (like the ImageMagick library). Since you are using Windows, please go to the Install ImageMagick on Windows page to download this library.
Once you have installed this library, you can install myQLM magics again:

python -m qat.magics.install

I hope it will fix your issue.

Thanks.
